services:
  app:
    build: .
    container_name: media_buying_management_system_app
    command: sh -c "uvicorn app.main:app --port 8000 --host 0.0.0.0"
    ports:
      - 8000:8000
    depends_on:
      - redis
    env_file:
      - .env.production

  redis:
     image: redis:7-alpine
     container_name: media_buying_management_system_redis
     ports:
       - 6379:6379
